Add missing option of example in __init__.py
**Description:**
Add missing option of example in libs/checkpoint-sqlite/langgraph/checkpoint/sqlite/__init__.py.

**Issue:**
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.

**Dependencies:**
N/A