docs: Enhance get_weather() in create-react-agent-memory.ipynb
get_weather() is unreliable.
1. The first user question "What's the weather in NYC?" will trigger validation error.
2. The second user question "What's it known for?" may trigger validation error or AssertionError().

config = {"configurable": {"thread_id": "1"}}
inputs = {"messages": [("user", "What's the weather in NYC?")]}

print_stream(graph.stream(inputs, config=config, stream_mode="values"))

================================ Human Message =================================

What's the weather in NYC?
================================== Ai Message ==================================
Tool Calls:
  get_weather (46f36dba-518b-4fa9-a5ab-3ae86ef8420a)
 Call ID: 46f36dba-518b-4fa9-a5ab-3ae86ef8420a
  Args:
    city: NYC
================================= Tool Message =================================
Name: get_weather

Error: 1 validation error for get_weather
city
  Input should be 'nyc' or 'sf' [type=literal_error, input_value='NYC', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
 Please fix your mistakes.
================================== Ai Message ==================================
...

inputs = {"messages": [("user", "What's it known for?")]}
print_stream(graph.stream(inputs, config=config, stream_mode="values"))

================================ Human Message =================================

What's it known for?
================================== Ai Message ==================================
Tool Calls:
  get_weather (1fa4276b-eb9c-4861-9cb1-92d4130507bd)
 Call ID: 1fa4276b-eb9c-4861-9cb1-92d4130507bd
  Args:
    city: NYC
================================= Tool Message =================================
Name: get_weather

Error: 1 validation error for get_weather
city
  Input should be 'nyc' or 'sf' [type=literal_error, input_value='NYC', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
 Please fix your mistakes.
================================== Ai Message ==================================
...

or

config = {"configurable": {"thread_id": "42"}}
inputs = {"messages": [("user", "What's it known for?")]}
print_stream(graph.stream(inputs, config=config, stream_mode="values"))

================================ Human Message =================================

What's it known for?
================================== Ai Message ==================================
Tool Calls:
  get_weather (fcfba04c-cef8-4f5c-8720-15736c3d4e08)
 Call ID: fcfba04c-cef8-4f5c-8720-15736c3d4e08
  Args:
    location: New York City
================================= Tool Message =================================
Name: get_weather

Error: AssertionError('Unknown Location')
 Please fix your mistakes.

Since we are demonstrating thread-level memory not human-in-the-loop, a string is more straightforward and reliable than AssertionError(), when dealing with 'Unknown Location'.